# the following module is intended to build a SIP pipeline for call initiation
# Recording Twilio API: https://www.twilio.com/docs/voice/api/recording

from fastapi import Query
from typing import Annotated
from fastapi import APIRouter
from twilio.rest import Client
from dotenv import load_dotenv
import requests, json, os, logging
from fastapi import Form, Response
from requests.auth import HTTPBasicAuth
import app.services.sip_server as sip_details
from app.models.sip_calling_models import UserCalling, CallRecording 

load_dotenv()
router=APIRouter()
open_json=open("app/app.json",'r')
conf_path=json.load(open_json)
database=list(conf_path.get("Databases").keys())[0]
ngrok_base_url_id="coalescent-unrespectfully-monique.ngrok-free.dev"
# ngrok_server_id="438d-122-162-150-88.ngrok-free.app"

# twilio configurations
TWILIO_SID = os.getenv("twilio_sid")
TWILIO_AUTH = os.getenv("twilio_auth_token")
twilio_number = os.getenv("sip_number")
client=Client(TWILIO_SID,TWILIO_AUTH)

# following api is to fetch the data from frontend basis of which the SIP session will the prepared  

@router.post("/generate_twiml")
async def make_twiml_file(to: str = Query(...)):
    twiml_response=f"""
    <Response>
        <Say>Connecting you to the customer now.</Say>
        <Dial 
            record="record-from-answer-dual"
            recordingStatusCallback="https://liwsozqcardxxobukntl.supabase.co/functions/v1/twilio"
            recordingStatusCallbackMethod="POST"
            recordingStatusCallbackEvent="completed">
            ${to}
        </Dial>
    </Response>
    """
    return Response(content=twiml_response.strip(), media_type="application/xml")

@router.post("/create_recording")
async def create_call_recording(recording: CallRecording):
    """
    Args:
        recording (Call Sid): The unique id generated after the call is initiated

    Returns:
        recording_url: The uri from the json response generated by the api
    """
    call_sid = recording.call_sid
    call_recording = client.calls(
        f"{call_sid}"
    ).recordings.create(recording_channels = "dual")
    logging.info(f"Generated Recording: {call_recording}")
    return {"Recording_URI": call_recording.uri},200

# @router.post("/call_status")
# async def check_call_status(request:Request):
#     """
#     The following api is used by twilio to make a 
#     POST request to check the call status .
#     """
#     json_body={}
#     response=await request.body()
#     twilio_data=response.decode().split("&")
#     for data in twilio_data:
#         key,value=data.split('=')
#         json_body[key]=value
#     base_path="/home/samarthjangda/testing/salesphony_testing/recordings"
#     call_status=json_body.get("CallStatus")
#     call_sid=json_body.get("CallSid")
#     recording_sid=json_body.get("RecordingSid")
#     if call_status == "completed":
#         print(f"Call is completed with sid:{call_sid} and now processing the same to ASR model")
#         # retrieve the recording
#         recording_data=client.recordings(recording_sid).fetch()
#         print(recording_data.uri)
#         recording_status=recording_data.status
#         while recording_status=='processing':
#             time.sleep(2)
#             recording_data=client.recordings(recording_sid).fetch()
#             recording_status=recording_data.status
#         recording_url=recording_data.uri.replace(".json",".wav")
#         audio_url=f"https://api.twilio.com/{recording_url}"
#         # check if recording is completed
#         save_recording=sip_details.get_recording(base_path,account_sid,auth_token,call_sid,audio_url)

@router.post("/get_recording")
async def get_recording(recording_url:Annotated[str,Form()],call_sid:Annotated[str,Form()]):
    """
    The following api is used to:
    1) Save the live call in the form of recording
    2) Fetch the transcript from the recording
    3) Fetch the entities based on the transcript 
    """
    base_path="/home/samarthjangda/testing/salesphony_testing/recordings"
    recording_url=recording_url.replace(".json",".wav")
    audio_url=f"https://api.twilio.com/{recording_url}"
    # check if recording is completed
    save_recording=sip_details.get_recording(base_path, TWILIO_SID, TWILIO_AUTH, call_sid,audio_url)

# prepare api for vonage 
# http://localhost:8000/voip_user_data
@router.post("/initiate_call")
async def get_user_data(customer_name:Annotated[str,Form()],client_number:Annotated[int,Form()],
                        call_type:Annotated[str,Form()],caller_name:Annotated[str,Form()],
                        call_date:Annotated[str,Form()]):
    # This will give the following data in parameters
    # authenticating the data recieved
    user_collection_name=conf_path.get("Databases").get(database).get("collections").get("usersdata")
    
    # authenticate_user=await sip_details.user_data_authentication(database,user_collection_name,username,number)
    
    # let's start initiating the call
    initiate_call = sip_details.make_call(client, twilio_number, str(client_number), ngrok_base_url_id)
    save_user_call_data = UserCalling(
        customer_name=customer_name,
        call_type=call_type,
        caller_name=caller_name,
        call_date=call_date,
        customer_number=str(client_number),
        call_sid=initiate_call.get("Calling_ID")
    )
    sip_details.save_user_call_data(save_user_call_data.model_dump())
    return {"StatusCode":200,"Message":"Call Initiated","CallUserData":save_user_call_data}

@router.get("/call_recording_transcript")
async def fetch_call_recording():
    """
    The following api is used to fetch the following:
        1) Recording of the call for the provided call sid.
        2) Transcript of the call using gpt-4o-transcribe model.
    """
    fetch_latest_data = sip_details.fetch_call_data()
    twilio_account_sid = os.getenv("twilio_sid")
    twilio_account_token = os.getenv("twilio_auth_token")
    if fetch_latest_data:
        # print(fetch_latest_data)
        call_id = fetch_latest_data[6]
        
        # function to fetch the twilio recording on the basis of call_sid
        recording = sip_details.fetch_twilio_call_recording(call_id)
        media_content = requests.get(
            recording.get("Recording URL"),
            auth = HTTPBasicAuth(twilio_account_sid,twilio_account_token)
        )
        local_path_to_save = r"C:\Users\Programming.com.DESKTOP-EVHMKR9\Desktop\development\rockland_ai\backend\data\audios"
        with open(f"{local_path_to_save}/audio.mp3", "wb") as audio_file:
            audio_file.write(media_content.content)
        return Response(content=media_content.content, media_type = "audio/mpeg")

@router.get("/call_transcript")
async def fetch_audio_transcript():
    """
    The following api is used to fetch the audio transcript
    """
    local_path_to_save = r"C:\Users\Programming.com.DESKTOP-EVHMKR9\Desktop\development\rockland_ai\backend\data\audios"
    
    fetch_transcript_json = sip_details.fetch_call_transcript(local_path_to_save)
    return {"AudioTranscript": fetch_transcript_json}